trigger:
- main
 
pool:
  vmImage: 'ubuntu-latest'
 
steps:
# 1. Install Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true
 
# 2. Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python dependencies'
 
# 3. Archive the app for deployment
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/streamlit_app.zip'
    replaceExistingArchive: true
 
# 4. Publish as pipeline artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/streamlit_app.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
 
# 5. Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: cb6255866a-vibecode06-az
    appName: CTS-VibeAppUK6103-5
    package: '$(Build.ArtifactStagingDirectory)/streamlit_app.zip'
