trigger:
  - main
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  pythonVersion: '3.10'
appFile: 'app.py'           # change if different
  artifactName: 'streamlit-drop'
zipName: 'app.zip'
 
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
 
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'
 
# copy repo files to staging (exclude venv and .git)
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      **/*
      !venv/**
      !.venv/**
      !**/.git/**
      !**/__pycache__/**
      !**/*.pyc
    TargetFolder: '$(Build.ArtifactStagingDirectory)/app'
 
# create a zip of staged folder
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/app'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(zipName)'
    replaceExistingArchive: true
 
# publish zip as pipeline artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(zipName)'
    ArtifactName: '$(artifactName)'
    publishLocation: 'Container'
