trigger:
  - main
 
pool:
  vmImage: 'ubuntu-latest'
 
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
 
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'
 
  # copy files to artifact staging folder (exclude venv, .git)
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: |
        **/*
        !venv/**
        !.venv/**
        !**/.git/**
        !**/*.pyc
        !__pycache__/**
      TargetFolder: '$(Build.ArtifactStagingDirectory)/app'
 
  # create a zip from staged folder
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/app'
      includeRootFolder: false
      archiveType: 'zip'
archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
      replaceExistingArchive: true
 
  # publish the zip as a pipeline artifact
  - task: PublishBuildArtifacts@1
    inputs:
PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
      ArtifactName: 'streamlit-drop'
      publishLocation: 'Container'
